# Generated by Django 6.1.1 on 2026-09-14 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('due_date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='semester',
            field=models.CharField(default='5th Semester', max_length=50),
        ),
    ]
